### ISSUE TITLE
Frameshift mutations

### ISSUE THREAD

**Issue by mbhall88** [samhorsfield96/ggCaller#11]
Love this method!

I'm trying to understand what would happen with the annotation/prediction process if a genome in the DBG has a frameshift mutation in a gene. Would that gene not get annotated? And would it mess up downstream annotations?

**Comment by samhorsfield96** [comment]
Hi, a frameshift will cause the sequence to be missed by the initial gene identification step. However, Panaroo includes a gene refining step, meaning that if intact homologues of the pseudogene are present in other genomes, the sequence should be found, clustered and functionally annotated, with an additional label of "potential pseudogene".

**Comment by mbhall88** [comment]
Ah very cool. Thanks for the explanation.
