### ISSUE TITLE
When using docker images, ggcaller does not work well

### ISSUE THREAD

**Issue by HirokiK0** [samhorsfield96/ggCaller#13]
We heard that there were problems with installation via conda, so we used docker as recommended. However, downloading the test dataset and using the commands listed in the documents did not work. Also, no error information is output, so I have no idea what is causing the problem. Please advise.

It appears that docker images is installed correctly as --help works.

Commands used.
cd test && docker run --rm -it -v $(pwd):/workdir samhorsfield96/ggcaller:latest ggcaller --refs pneumo_CL_group2.txt

**Comment by HirokiK0** [comment]
Thanks for the reply.
I have tried two operating systems, ubuntu 20.04 and ubuntu 22.04 on wsl2.

There was no output at all.

The pneumo_CL_group2.txt is the same as the one in the test folder on github. So it only contained the file name.

I personally presume that it is a permissions issue, but changing the workdir permissions by chmod 777 had no effect. Also, building the docker image on my PC did not work.

**Comment by samhorsfield96** [comment]
Hi, I would suggest trying two things:

- Try regenerating the input.txt file for the test sequence using the command documented [here](https://ggcaller.readthedocs.io/en/latest/quickstart.html), this will use absolute file paths which may be causing the issue.
- If that does not work, install ggCaller from source, documented [here](https://ggcaller.readthedocs.io/en/latest/installation.html)

Please let me know whether you still run into trouble.

**Comment by HirokiK0** [comment]
Building coloured compacted DBG...
Generating graph stop codon index...
Mapping contigs to graph...
Downloading databases...
Traceback (most recent call last):

**Comment by samhorsfield96** [comment]
There could be a number of reasons for this, and unfortunately I have not been able to replicate this issue. To circumvent the download, you can navigate to the `models` directory where you installed ggCaller from source, and run `wget https://ftp.ebi.ac.uk/pub/databases/pp_dbs/ggCallerdb.tar.bz2` to download the model database. You should then be able to run ggCaller as before.

**Comment by HirokiK0** [comment]
Test data worked fine! Thank you very much for your very courteous response!
