### ISSUE TITLE
HMMER3

### ISSUE THREAD

**Issue by davidmadariaga** [samhorsfield96/ggCaller#14]
Hi. Hope you are doing great!., could you help me please? what does this means?  where should i install HMMER3? sorry for being this dumb, i really doesnt know about this kind of things. I just installed it from source, using mamba, following the instructions on github. I'd be really thankful if you answer me, whenever you can. 
Cheers from Chile, South America. 

![GGCALLERHMMER](https://github.com/samhorsfield96/ggCaller/assets/25496906/28064a15-b57d-4bc7-8b05-6d4a7192fce1)

**Comment by samhorsfield96** [comment]
Hi David, 

I just need a few bits of information to help with debugging:

- How did you install ggCaller?
- What command did you run using ggCaller?
- What is the output when you run `hmmscan -h`?
- What is the output when you run `mamba list`? If this is too large, you can save this to a file using `mamba list > mamba_list.txt` and send the file across.

**Comment by davidmadariaga** [comment]
Hi, thanks for answering, you are very kind!

I first write this command on a server: nohup ggcaller --refs input.txt --threads 50 &. The nohup.out file contains this:
(base) [mdavid@soroban IMSAR217cc11]$ cat nohup.out 
Building coloured compacted DBG...
Generating graph stop codon index...
Mapping contigs to graph...
Need HMMER3 to be installed and available in PATH  
Downloading databases...

Building coloured compacted DBG...
Generating graph stop codon index...
Mapping contigs to graph...
Need HMMER3 to be installed and available in PATH 


then i installed ggcaller on my laptop, and then i run it using ggcaller --refs input.txt --threads 5. It ended up giving me the same message "Need HMMER3 to be installed and available in PATH ".

This is what appears when i write hmmscan -h:
![hmmscanh](https://github.com/samhorsfield96/ggCaller/assets/25496906/29f761bc-178b-4195-9c6d-694f035a9b27)



And this when i write mamba list: 
[mambalist.txt](https://github.com/samhorsfield96/ggCaller/files/13441918/mambalist.txt)



Thanks again, in advance.

Cheers

**Comment by samhorsfield96** [comment]
Hi David, thanks for sending all of this information through. This was very helpful, I was able to identify the issue (it was due to an update to HMMER3), this is now fixed in commit [1d85587](https://github.com/samhorsfield96/ggCaller/commit/1d85587b9e612d4ec23ff8c71ae6031c56cab20a). Please update to the latest commit and rerun `python setup.py install`
