### ISSUE TITLE
python error (probably)

### ISSUE THREAD

**Issue by davidmadariaga** [samhorsfield96/ggCaller#16]
Hi, Mr., thanks for the last answer, you were really kind!, it seems that now i have another issue. I reinstalled it using source again, from this step "conda env create -f environment_linux.yml"

unfortunately, this is what i get:

(ggc_env) [mdavid@soroban IMSAR217cc11]$ nohup ggcaller --refs input.txt --threads 50 &
[1] 356615
(ggc_env) [mdavid@soroban IMSAR217cc11]$ nohup: ignoring input and appending output to ‘nohup.out’
jobs
[1]+  Running                 nohup ggcaller --refs input.txt --threads 50 &
(ggc_env) [mdavid@soroban IMSAR217cc11]$ cat nohup.out 
Building coloured compacted DBG...
(ggc_env) [mdavid@soroban IMSAR217cc11]$ cat nohup.out 
Building coloured compacted DBG...
(ggc_env) [mdavid@soroban IMSAR217cc11]$ ls -lh
total 479M
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 113198_DE14151_PacBio.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 113205_DE14168_PacBio.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 122164_18_122_hybrid.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 122165_18_62_hybrid.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 2290_M7124.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 31317_NM3686.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 31318_NM3682.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 31319_M10208.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 31332_NM3683.fasta
-rw-r--r-- 1 mdavid bioren 2,1M nov 21 19:58 36448_2636.fasta
-rw-r--r-- 1 mdavid bioren 2,1M nov 21 19:58 36449_2639.fasta
-rw-r--r-- 1 mdavid bioren 2,1M nov 21 19:58 36450_2644.fasta
-rw-r--r-- 1 mdavid bioren 2,1M nov 21 19:58 36451_2652.fasta
-rw-r--r-- 1 mdavid bioren 2,1M nov 21 19:58 36452_2664.fasta
-rw-r--r-- 1 mdavid bioren 2,1M nov 21 19:58 36453_2665.fasta
-rw-r--r-- 1 mdavid bioren 2,1M nov 21 19:58 36454_1982.fasta
-rw-r--r-- 1 mdavid bioren 2,1M nov 21 19:58 36455_1983.fasta
-rw-r--r-- 1 mdavid bioren 2,1M nov 21 19:58 36456_1984.fasta
-rw-r--r-- 1 mdavid bioren 2,1M nov 21 19:58 36457_1985.fasta
-rw-r--r-- 1 mdavid bioren 2,1M nov 21 19:58 36458_1986.fasta
-rw-r--r-- 1 mdavid bioren 2,1M nov 21 19:58 36459_1987.fasta
-rw-r--r-- 1 mdavid bioren 2,1M nov 21 19:58 36461_2560.fasta
-rw-r--r-- 1 mdavid bioren 2,1M nov 21 19:58 36462_1981.fasta
-rw-r--r-- 1 mdavid bioren 2,1M nov 21 19:58 36463_2380.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 36689_M25543.fasta
-rw-r--r-- 1 mdavid bioren 2,1M nov 21 19:58 36848_2593.fasta
-rw-r--r-- 1 mdavid bioren 2,1M nov 21 19:58 36849_2585.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 39628_82_15.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 39629_83_15.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 39630_111_15.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 39632_171_15.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 39633_179_15.fasta
-rw-r--r-- 1 mdavid bioren 2,1M nov 21 19:58 39634_583_15.fasta
-rw-r--r-- 1 mdavid bioren 2,1M nov 21 19:58 39638_666_15.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 39641_1010_15.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 39645_1064_15.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 39647_1082_15.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 39649_1083_15.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 39650_1090_15.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 39651_1096_15.fasta
-rw-r--r-- 1 mdavid bioren 2,1M nov 21 19:58 39775_1658_15.fasta
-rw-r--r-- 1 mdavid bioren 2,1M nov 21 19:58 39781_1847_15.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 39791_2029_15.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 39795_2099_15.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 39797_2143_15.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 39798_2146_15.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 39812_2749_15.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 39827_3833_15.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 39836_M03473.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 39837_M05730.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 39842_M04874.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 39845_M03564.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 39846_M05451.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 39847_M05831.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 39849_M05731.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 39850_M05732.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 39851_M05733.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 39855_M05737.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 39859_M05738.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 39861_M00601.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 39865_M21374.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 39866_M21427.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 39867_M21428.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 39870_M21716.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 39871_M21717.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 39878_M26925.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 39879_M26926.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 39880_M26919.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 39882_M25670.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 39883_M26294.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 39884_M26295.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 39889_M26949.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 39892_M26017.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 39893_M26263.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 39896_M27267.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 39898_M26089.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 39899_M25964.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 39900_M26087.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 39901_M26088.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 39903_M26416.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 41785_2838.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 41787_0393_93.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 42848_M26242.fasta
-rw-r--r-- 1 mdavid bioren 2,0M nov 21 19:58 45110_M23151.fasta
-rw-r--r-- 1 mdavid bioren 2,1M nov 21 19:58 45113_M23599.fasta
-rw-r--r-- 1 mdavid bioren 2,1M nov 21 19:58 45114_M23600.fasta
-rw-r--r-- 1 mdavid bioren 2,0M nov 21 19:58 45115_M23677.fasta
-rw-r--r-- 1 mdavid bioren 2,1M nov 21 19:58 45118_M25165.fasta
-rw-r--r-- 1 mdavid bioren 2,0M nov 21 19:58 45119_M25241.fasta
-rw-r--r-- 1 mdavid bioren 2,0M nov 21 19:58 45120_M25244.fasta
-rw-r--r-- 1 mdavid bioren 2,1M nov 21 19:58 45121_M25633.fasta
-rw-r--r-- 1 mdavid bioren 2,1M nov 21 19:58 45122_M25635.fasta
-rw-r--r-- 1 mdavid bioren 2,1M nov 21 19:58 45124_M25683.fasta
-rw-r--r-- 1 mdavid bioren 2,1M nov 21 19:58 45125_M25684.fasta
-rw-r--r-- 1 mdavid bioren 2,1M nov 21 19:58 45127_M25688.fasta
-rw-r--r-- 1 mdavid bioren 2,1M nov 21 19:58 45128_M25874.fasta
-rw-r--r-- 1 mdavid bioren 2,0M nov 21 19:58 45133_M26021.fasta
-rw-r--r-- 1 mdavid bioren 2,0M nov 21 19:58 45138_M26093.fasta
-rw-r--r-- 1 mdavid bioren 2,0M nov 21 19:58 45139_M26247.fasta
-rw-r--r-- 1 mdavid bioren 2,0M nov 21 19:58 45157_M27458.fasta
-rw-r--r-- 1 mdavid bioren 2,0M nov 21 19:58 45158_M27459.fasta
-rw-r--r-- 1 mdavid bioren 2,0M nov 21 19:58 45159_M27471.fasta
-rw-r--r-- 1 mdavid bioren 2,0M nov 21 19:58 45161_M27885.fasta
-rw-r--r-- 1 mdavid bioren 2,0M nov 21 19:58 45167_M28971.fasta
-rw-r--r-- 1 mdavid bioren 2,0M nov 21 19:58 45168_M28979.fasta
-rw-r--r-- 1 mdavid bioren 2,1M nov 21 19:58 45172_M29225.fasta
-rw-r--r-- 1 mdavid bioren 2,1M nov 21 19:58 45173_M29276.fasta
-rw-r--r-- 1 mdavid bioren 2,1M nov 21 19:58 45181_M37929.fasta
-rw-r--r-- 1 mdavid bioren 2,1M nov 21 19:58 45184_M38252.fasta
-rw-r--r-- 1 mdavid bioren 2,1M nov 21 19:58 45185_M38355.fasta
-rw-r--r-- 1 mdavid bioren 2,1M nov 21 19:58 45187_M38738.fasta
-rw-r--r-- 1 mdavid bioren 2,1M nov 21 19:58 45188_M38741.fasta
-rw-r--r-- 1 mdavid bioren 2,1M nov 21 19:58 45189_M38742.fasta
-rw-r--r-- 1 mdavid bioren 2,1M nov 21 19:58 45190_M38917.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 45893_L91543.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 46977_DE8555.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 46979_M07149.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 46980_M07161.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 46981_M07162.fasta
-rw-r--r-- 1 mdavid bioren 2,1M nov 21 19:58 46982_M08000.fasta
-rw-r--r-- 1 mdavid bioren 2,1M nov 21 19:58 46983_M08001.fasta
-rw-r--r-- 1 mdavid bioren 2,1M nov 21 19:58 46984_M09261.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 46985_M12752.fasta
-rw-r--r-- 1 mdavid bioren 2,1M nov 21 19:58 46986_M22191.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 46987_M22718.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 46988_M22722.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 46989_M22740.fasta
-rw-r--r-- 1 mdavid bioren 2,1M nov 21 19:58 46991_M22748.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 46992_M22759.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 46993_M22769.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 46994_M22772.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 46996_M22801.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 47003_M23413.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 47005_M25070.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 47006_M25087.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 47007_M25419.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 47008_M25438.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 47009_M25472.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 47010_M25476.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 47011_M27559.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 47012_WUE2121.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 47233_CNM3.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 47234_M40240.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 47235_M21273.fasta
-rw-r--r-- 1 mdavid bioren 2,1M nov 21 19:58 49271_NM3.fasta
-rw-r--r-- 1 mdavid bioren 2,1M nov 21 19:58 49272_NM4.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 57572_11_590_251.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 57573_12_590_208.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 57574_14_590_159.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 57575_14_590_627.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 57577_NEIS_15_193.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 57578_NEIS_15_198.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 57579_NEIS_15_215.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 57580_NEIS_15_236.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 57582_NEIS_16_92.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 57583_NEIS_16_306.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 57584_NEIS_16_579.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 58230_M25462.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 58253_M25456.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 58271_M25459.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 58300_M25439.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 58322_M25474.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 58347_M25073.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 58348_M25074.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 62972_M22718.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 62984_DW8555.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 62986_WUE2121.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 62987_3683.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 62988_M07149.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 62989_M07162.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 62991_M25459.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 698_FAM18.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 81898_11_251_2.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 81899_12_208_2.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 81900_14_159_2.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 81901_14_627_2.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 81902_15_123_2.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 81904_15_198_2.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 81905_15_215_2.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 81907_16_7_2.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 81908_16_92_2.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 81909_16_306_2.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 81910_16_579_2.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 82040_11_251_3.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 82041_12_208_3.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 82043_14_627_3.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 82044_15_123_3.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 82045_15_193_3.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 82046_15_198_3.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 82048_15_236_3.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 82049_16_7_3.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 82050_16_92_3.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 82051_16_306_3.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 82052_16_579_3.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 82218_14_159_3.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 82219_NEIS_15_123.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 82220_15_193_2.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 82221_15_215_3.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 82222_15_236_2.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 82224_NEIS_16_7.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 84413_DL20404.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 85163_M22803.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 95884_11_251.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 95885_12_208.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 95886_14_159.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 95887_14_627.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 95888_15_123.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 95889_15_193.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 95890_15_198.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 95891_15_215.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 95892_15_236.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 95893_16_7.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 95894_16_92.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 95895_16_306.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 95896_16_579.fasta
-rw-r--r-- 1 mdavid bioren 2,2M nov 21 19:58 97476_M23405.fasta
-rw-r--r-- 1 mdavid bioren 2,1M nov 21 19:58 97883_Nmiss3092.fasta
drwxr-xr-x 2 mdavid bioren   10 nov 25 02:09 ggCaller_output
-rw-r--r-- 1 mdavid bioren 4,8M nov 25 02:10 input.color.bfg
-rw-r--r-- 1 mdavid bioren  19M nov 25 02:10 input.gfa
-rw-r--r-- 1 mdavid bioren  14K nov 25 02:06 input.txt
-rw------- 1 mdavid bioren   72 nov 25 02:10 nohup.out
(ggc_env) [mdavid@soroban IMSAR217cc11]$ cat nohup.out 
Building coloured compacted DBG...
Generating graph stop codon index...
Mapping contigs to graph...
Downloading databases...
Traceback (most recent call last):
  File "/home/bioren/mdavid/.conda/envs/ggc_env/lib/python3.9/urllib/request.py", line 1346, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/home/bioren/mdavid/.conda/envs/ggc_env/lib/python3.9/http/client.py", line 1285, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/bioren/mdavid/.conda/envs/ggc_env/lib/python3.9/http/client.py", line 1331, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/bioren/mdavid/.conda/envs/ggc_env/lib/python3.9/http/client.py", line 1280, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/bioren/mdavid/.conda/envs/ggc_env/lib/python3.9/http/client.py", line 1040, in _send_output
    self.send(msg)
  File "/home/bioren/mdavid/.conda/envs/ggc_env/lib/python3.9/http/client.py", line 980, in send
    self.connect()
  File "/home/bioren/mdavid/.conda/envs/ggc_env/lib/python3.9/http/client.py", line 1454, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/home/bioren/mdavid/.conda/envs/ggc_env/lib/python3.9/ssl.py", line 501, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/bioren/mdavid/.conda/envs/ggc_env/lib/python3.9/ssl.py", line 1074, in _create
    self.do_handshake()
  File "/home/bioren/mdavid/.conda/envs/ggc_env/lib/python3.9/ssl.py", line 1343, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bioren/mdavid/.conda/envs/ggc_env/bin/ggcaller", line 33, in <module>
    sys.exit(load_entry_point('ggCaller==1.3.4', 'console_scripts', 'ggcaller')())
  File "/home/bioren/mdavid/.conda/envs/ggc_env/lib/python3.9/site-packages/ggCaller-1.3.4-py3.9-linux-x86_64.egg/ggCaller/__main__.py", line 436, in main
    db_dir = download_db()
  File "/home/bioren/mdavid/.conda/envs/ggc_env/lib/python3.9/site-packages/ggCaller-1.3.4-py3.9-linux-x86_64.egg/models/__main__.py", line 15, in download_db
    filename = wget.download(url, out=module_dir)
  File "/home/bioren/mdavid/.conda/envs/ggc_env/lib/python3.9/site-packages/wget.py", line 526, in download
    (tmpfile, headers) = ulib.urlretrieve(binurl, tmpfile, callback)
  File "/home/bioren/mdavid/.conda/envs/ggc_env/lib/python3.9/urllib/request.py", line 239, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/home/bioren/mdavid/.conda/envs/ggc_env/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/home/bioren/mdavid/.conda/envs/ggc_env/lib/python3.9/urllib/request.py", line 517, in open
    response = self._open(req, data)
  File "/home/bioren/mdavid/.conda/envs/ggc_env/lib/python3.9/urllib/request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/home/bioren/mdavid/.conda/envs/ggc_env/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/home/bioren/mdavid/.conda/envs/ggc_env/lib/python3.9/urllib/request.py", line 1389, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/home/bioren/mdavid/.conda/envs/ggc_env/lib/python3.9/urllib/request.py", line 1349, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 104] Connection reset by peer>
[1]+  Exit 1                  nohup ggcaller --refs input.txt --threads 50

Sorry for being a pain in the ass. 

Cheers

**Comment by samhorsfield96** [comment]
Please see reply in issue https://github.com/samhorsfield96/ggCaller/issues/13#issuecomment-1827464891.

**Comment by samhorsfield96** [comment]
Hi David, sorry for the confusion. I would suggest still running it as you are from source, but following the guidance below: 

1. navigate to the `models` directory located in the `ggCaller` source directory
2. Run `wget https://ftp.ebi.ac.uk/pub/databases/pp_dbs/ggCallerdb.tar.bz2` to download the model database. 
3. Run ggCaller as before.

**Comment by davidmadariaga** [comment]
you are so kind, thank you very much. That worked, have a great day, Mr., Take care. 

Cheers
