### ISSUE TITLE
Error while following tutorial! Please help!

### ISSUE THREAD

**Issue by Vladislav-Shevtsov** [samhorsfield96/ggCaller#2]
I installed the application using conda. Then downloaded test data from the tutorial (https://github.com/samhorsfield96/ggCaller/blob/master/docs/tutorial.rst) and get the error message (Illegal instruction (core dumped)) after running the command:
 `ggcaller --refs Bentley_et_al_2006_CPS_sequences/input.txt --annotation ultrasensitive --diamonddb Bentley_et_al_2006_CPS_protein_sequences.faa --aligner def --alignment pan --save --out ggc_Bentley_et_al_CPS --threads 4` 

Please advice how to solve it! Looking forward to your answer!

P.S. I have ensured that the input.txt file is generated and path to the file was set correctly.

**Comment by samlipworth** [comment]
See my previous issue -this is due to a conda dependency - did you try installing from source (I couldn't get this to work (on an ubuntu machine) either but will give it another go.

**Comment by samhorsfield96** [comment]
If this doesn't work, I would suggest installing gcc via conda (https://anaconda.org/conda-forge/cxx-compiler) and retrying.

**Comment by samlipworth** [comment]
can confirm the above works for me

**Comment by samhorsfield96** [comment]
@Vladislav-Shevtsov have you been able to install? If all is good I shall close the issue.
