### ISSUE TITLE
biopython should be pinned at version 1.7.9 to avoid errors when building from source (with mamba)

### ISSUE THREAD

**Issue by benrhodes26** [samhorsfield96/ggCaller#7]
I originally built from source using the .yml provided (using mamba), and version 1.8.1 of biopython was installed. This yields errors when running ggcaller since the class UnknownSeq has been removed in this version.

I then tried pinning biopython to 1.7.8 (since biopython declared the removal of UnknownSeq in the 1.7.9 release notes). This was *almost* fine, until quite late on in the ggcaller pipeline, when a different biopython error occurs (this new error only occurs in <1.7.9)

It looks like v 1.7.9 is the *only* version that will work (because it apparently does contain UnknownSeq still, just deprecated).

Meta-point: it may be possible that conda does stricter dependency checks than mamba (?) and this problem didn't occur for others using conda.

**Comment by samhorsfield96** [comment]
Hi Ben, many thanks for looking into this. I believe the problem is coming from bcbio-gff, which imports the deprecated UnknownSeq object. Using biopython 1.79 or 1.80 should fix this.

**Comment by samhorsfield96** [comment]
I’ve now pinned biopython to v1.80 in both environment.yml files. Thanks again for your help with this.

**Comment by benrhodes26** [comment]
Great! Thanks :)
